### TEST GET / website

GET http://localhost:1222

### dashboard
GET http://localhost:1222/dashboard

### API / GET
GET http://localhost:1222/api/data

### API / POST
POST http://localhost:1222/api/data

Content-Type: application/json

{
   "name": "Dinesh"
}